In [8]:
import numpy as np
from numpy import array

In [12]:
myData = np.array([0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])
myData

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [13]:
array([0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [14]:
myData.shape[0]

14

In [15]:
myTs = myData.sum()

In [16]:
def clacProb(myPriorCount, myCount):
  return myPriorCount/myCount

In [17]:
clacProb(myTs, myData.shape[0])

0.5

In [18]:
myFs = 1 - clacProb(myTs, myData.shape[0])

In [19]:
myFs

0.5

### Given the minecraft foundational model. How would we apply probability to the model and what's the agent?
**Ans:** In the Minecraft foundational model, probability is applied to guide the agent's decision-making under uncertainty, using stochastic policies to choose actions based on their likelihood of success, modeling environmental randomness, or balancing exploration and exploitation. The agent, a simulated entity within the Minecraft world, perceives its surroundings, takes actions like mining or building, and operates towards goals defined by a reward system. This probabilistic approach enables the agent to adapt and perform complex tasks in dynamic and uncertain environments.